FROM java:8

RUN mkdir -p /var/lib/om-kafka

WORKDIR /var/lib/om-kafka

RUN wget https://mirror-hk.koddos.net/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
        tar -xzvf apache-maven-3.6.3-bin.tar.gz

ENV MAVEN_HOEM=/var/lib/om-kafka/apache-maven-3.6.3

ENV PATH=$MAVEN_HOEM/bin:$PATH

MAINTAINER zhongjun <jun.zhongjun2@gmail.com>

RUN git clone https://gitee.com/opensourceway/om-kafka.git && \
        cd om-kafka && \
        mvn clean install assembly:single  -Dmaven.test.skip && \
        mv ./target/omkafka-1.0-SNAPSHOT.jar ../om-kafka.jar

CMD java -jar om-kafka.jar
