FROM openjdk:8-jdk

RUN mkdir -p /var/lib/om-kafka

WORKDIR /var/lib/om-kafka

# Install basic software support
RUN apt-get update && \
    apt-get install --yes software-properties-common

RUN wget https://mirror-hk.koddos.net/apache/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz && \
        tar -xzvf apache-maven-3.8.8-bin.tar.gz

ENV MAVEN_HOEM=/var/lib/om-kafka/apache-maven-3.8.8

ENV PATH=$MAVEN_HOEM/bin:$PATH

MAINTAINER zhongjun <jun.zhongjun2@gmail.com>

RUN git clone https://gitee.com/opensourceway/om-kafka.git && \
        cd om-kafka && \
        mvn clean install assembly:single  -Dmaven.test.skip && \
        mv ./target/omkafka-1.0-SNAPSHOT.jar ../om-kafka.jar

CMD java -jar om-kafka.jar
